# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'Test'
url:              http://tekulvw.io
baseurl:          /

author:
  name:           'Will Tekulve'
  url:            https://github/tekulvw

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tekulvw/tekulvw.github.io
