theme: jekyll-theme-cayman

# Setup
title: tekulvw.io
# tagline:      A responsive theme for your project on GitHub Pages
baseurl: ""
# paginate:     1

# About/contact
author:
  name: Will Tekulve
  url: http://tekulvw.io

# Gems
# gems:
#  - jekyll-paginate

# Others
# markdown: kramdown